### ISSUE TITLE
fails with ruby 2.3.1

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_cli#5]
Hi,

Trying to use this gem with Ruby 2.3.1 and it blows out on not finding activesupport =2.3.0 which is amusing seeing as activesupport is now at version 5.0

**Comment by highbass** [comment]
any solutions for this?

**Comment by resistorsoftware** [comment]
I have not looked into it closer. Must be a pooched dependency somewhere:

     ruby -v
     ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
     dlazar@Davids-iMac [13:08:37] [~]
     -> % gem install shopify_cli
         ERROR:  Could not find a valid gem 'activesupport' (= 2.3.0) in any repository
         ERROR:  Possible alternatives: activesupport

With these gems in place... 

     gem list

    *** LOCAL GEMS ***

    actioncable (5.0.0)
    actionmailer (5.0.0, 4.2.6, 4.2.5)
    actionpack (5.0.0, 4.2.6, 4.2.5)
    actionview (5.0.0, 4.2.6, 4.2.5)
    activejob (5.0.0, 4.2.6, 4.2.5)
    activemodel (5.0.0, 4.2.6, 4.2.5)
    activemodel-serializers-xml (1.0.1)
    activerecord (5.0.0, 4.2.6, 4.2.5)
    activeresource (4.0.0)
    activesupport (5.0.0, 4.2.6, 4.2.5)

**Comment by chainsol** [comment]
This happens for me too - it's looking for activesupport 2.3, which is pretty old, haha.

I don't seem to understand though, the gemspec calls for a newer version, doesn't it?

**Comment by andrewmarconi** [comment]
I ran into the same problem, but had success by installing `shopify_api` and `shopify_client` first, and then attempting to install `shopify_cli`. Some hosed dependencies that get ignored if api and client are already in place, I guess?

```
$ gem install shopify_api
$ gem install shopify_client
$ gem install shopify_cli
```

Here's the output:

```
$ gem install shopify_client

Fetching: multi_json-1.12.1.gem (100%)
Successfully installed multi_json-1.12.1
Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.9.2.gem (100%)
Successfully installed faraday-0.9.2
Fetching: shopify_client-0.0.1.gem (100%)
Successfully installed shopify_client-0.0.1
Parsing documentation for multi_json-1.12.1
Installing ri documentation for multi_json-1.12.1
invalid options: -SHN
(invalid options are ignored)
Parsing documentation for multipart-post-2.0.0
Installing ri documentation for multipart-post-2.0.0
Parsing documentation for faraday-0.9.2
Installing ri documentation for faraday-0.9.2
Parsing documentation for shopify_client-0.0.1
Installing ri documentation for shopify_client-0.0.1
Done installing documentation for multi_json, multipart-post, faraday, shopify_client after 1 seconds
4 gems installed

$ gem install shopify_api

Fetching: activesupport-4.2.7.1.gem (100%)
Successfully installed activesupport-4.2.7.1
Fetching: builder-3.2.2.gem (100%)
Successfully installed builder-3.2.2
Fetching: activemodel-4.2.7.1.gem (100%)
Successfully installed activemodel-4.2.7.1
Fetching: rails-observers-0.1.2.gem (100%)
Successfully installed rails-observers-0.1.2
Fetching: activeresource-4.1.0.gem (100%)
Successfully installed activeresource-4.1.0
Fetching: rack-2.0.1.gem (100%)i
Successfully installed rack-2.0.1
Fetching: shopify_api-4.3.0.gem (100%)
Successfully installed shopify_api-4.3.0
Parsing documentation for activesupport-4.2.7.1
Installing ri documentation for activesupport-4.2.7.1
Parsing documentation for builder-3.2.2
Installing ri documentation for builder-3.2.2
Parsing documentation for activemodel-4.2.7.1
Installing ri documentation for activemodel-4.2.7.1
Parsing documentation for rails-observers-0.1.2
Installing ri documentation for rails-observers-0.1.2
Parsing documentation for activeresource-4.1.0
Installing ri documentation for activeresource-4.1.0
Parsing documentation for rack-2.0.1
Installing ri documentation for rack-2.0.1
Parsing documentation for shopify_api-4.3.0
Installing ri documentation for shopify_api-4.3.0
Done installing documentation for activesupport, builder, activemodel, rails-observers, activeresource, rack, shopify_api after 11 seconds
7 gems installed

$ gem install shopify_cli

Fetching: coderay-1.1.1.gem (100%)
Successfully installed coderay-1.1.1
Fetching: slop-3.6.0.gem (100%)
Successfully installed slop-3.6.0
Fetching: method_source-0.8.2.gem (100%)
Successfully installed method_source-0.8.2
Fetching: pry-0.10.4.gem (100%)
Successfully installed pry-0.10.4
Fetching: thor-0.18.1.gem (100%)
Successfully installed thor-0.18.1
Successfully installed shopify_cli-1.0.1
invalid options: -SNw2
(invalid options are ignored)
Parsing documentation for coderay-1.1.1
Installing ri documentation for coderay-1.1.1
Parsing documentation for slop-3.6.0
Installing ri documentation for slop-3.6.0
Parsing documentation for method_source-0.8.2
Installing ri documentation for method_source-0.8.2
Parsing documentation for pry-0.10.4
Installing ri documentation for pry-0.10.4
Parsing documentation for thor-0.18.1
Installing ri documentation for thor-0.18.1
Parsing documentation for shopify_cli-1.0.1
Installing ri documentation for shopify_cli-1.0.1
Done installing documentation for coderay, slop, method_source, pry, thor, shopify_cli after 6 seconds
6 gems installed
```

**Comment by vfonic** [comment]
:+1:

**Comment by chainsol** [comment]
Above solution also does not work for me - Ruby 2.3.1.

**Comment by stahtews** [comment]
Anyone found the solution ? none of the above seem to work for me :(
below is the error when i run bundle install on windows. following the video on vimeo, create shopify app in 5 mins.

Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (= 5.0.0.1)

  In Gemfile:
rails (>= 5.0.0.1, ~> 5.0.0) x86-mingw32 was resolved to 5.0.0.1, which
depends on
activemodel (= 5.0.0.1) x86-mingw32 was resolved to 5.0.0.1, which depends
on
        activesupport (= 5.0.0.1) x86-mingw32

rails (>= 5.0.0.1, ~> 5.0.0) x86-mingw32 was resolved to 5.0.0.1, which
depends on
activemodel (= 5.0.0.1) x86-mingw32 was resolved to 5.0.0.1, which depends
on
        activesupport (= 5.0.0.1) x86-mingw32

rails (>= 5.0.0.1, ~> 5.0.0) x86-mingw32 was resolved to 5.0.0.1, which
depends on
activemodel (= 5.0.0.1) x86-mingw32 was resolved to 5.0.0.1, which depends
on
        activesupport (= 5.0.0.1) x86-mingw32

rails (>= 5.0.0.1, ~> 5.0.0) x86-mingw32 was resolved to 5.0.0.1, which
depends on
activemodel (= 5.0.0.1) x86-mingw32 was resolved to 5.0.0.1, which depends
on
        activesupport (= 5.0.0.1) x86-mingw32

rails (>= 5.0.0.1, ~> 5.0.0) x86-mingw32 was resolved to 5.0.0.1, which
depends on
activemodel (= 5.0.0.1) x86-mingw32 was resolved to 5.0.0.1, which depends
on
        activesupport (= 5.0.0.1) x86-mingw32

rails (>= 5.0.0.1, ~> 5.0.0) x86-mingw32 was resolved to 5.0.0.1, which
depends on
activemodel (= 5.0.0.1) x86-mingw32 was resolved to 5.0.0.1, which depends
on
        activesupport (= 5.0.0.1) x86-mingw32

rails (>= 5.0.0.1, ~> 5.0.0) x86-mingw32 was resolved to 5.0.0.1, which
depends on
activemodel (= 5.0.0.1) x86-mingw32 was resolved to 5.0.0.1, which depends
on
        activesupport (= 5.0.0.1) x86-mingw32

    shopify_app (= 7.1.0) x86-mingw32 was resolved to 7.1.0, which depends on
      shopify_api (>= 4.2.2) x86-mingw32 was resolved to 4.2.2, which depends

        activeresource x86-mingw32 was resolved to 2.0.1, which depends on
          activesupport (= 2.0.1) x86-mingw32

rails (>= 5.0.0.1, ~> 5.0.0) x86-mingw32 was resolved to 5.0.0.1, which
depends on
actionmailer (= 5.0.0.1) x86-mingw32 was resolved to 5.0.0.1, which
depends on
activejob (= 5.0.0.1) x86-mingw32 was resolved to 5.0.0.1, which depends
on
globalid (>= 0.3.6) x86-mingw32 was resolved to 0.3.7, which depends
on
            activesupport (>= 4.1.0) x86-mingw32

    jbuilder (~> 2.5) x86-mingw32 was resolved to 2.6.0, which depends on
      activesupport (< 5.1, >= 3.0.0) x86-mingw32

rails (>= 5.0.0.1, ~> 5.0.0) x86-mingw32 was resolved to 5.0.0.1, which
depends on
actionmailer (= 5.0.0.1) x86-mingw32 was resolved to 5.0.0.1, which
depends on
rails-dom-testing (~> 2.0) x86-mingw32 was resolved to 2.0.1, which
depends on
          activesupport (< 6.0, >= 4.2.0) x86-mingw32

rails (>= 5.0.0.1, ~> 5.0.0) x86-mingw32 was resolved to 5.0.0.1, which
depends on
sprockets-rails (>= 2.0.0) x86-mingw32 was resolved to 3.2.0, which
depends on
        activesupport (>= 4.0) x86-mingw32

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by vfonic** [comment]
I've cloned the git repo, ran `bundle install` inside of the repo folder and then ran `rake install`.

**Comment by resistorsoftware** [comment]
This remains a sickly bear... running shopify-cli now pukes like this with a latest Ruby 2.3.3

shopify-cli
/Users/foo/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2159:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fc98ec279e0 activesupport-4.2.7> (NoMethodError)

**Comment by charlesemarsh** [comment]
/Users/xxx/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2159:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fed2242d944 activeresource-4.1.0> (NoMethodError)

**Comment by lukeshumard** [comment]
Same issue for me.

**Comment by perakeney** [comment]
Fixed:
Install gem shopify_api
https://rubygems.org/gems/shopify_api

**Comment by wnm** [comment]
I think it nothing to do with your ruby version, but your rails version.

For rails 5:

The latest release of activeresource on rubygems (https://rubygems.org/gems/activeresource) is 4.1.0

The 4.x branch of activeresource, depends on activesupport 4.x

    activeresource (~> 4.0) was resolved to 4.0.0, which depends on
      activesupport (~> 4.0)


But rails 5, depends on activesupport 5.x

    rails (~> 5) was resolved to 5.0.0, which depends on
      activesupport (= 5.0.0)

From the activesupport README about rails 5 compatibility (https://github.com/rails/activeresource):

"For compatibility with Rails 5, use:"

    gem 'activeresource', github: 'rails/activeresource', branch: 'master'  


So in your Gemfile, of a rails 5 app, you should have this:

    gem 'rails', '~> 5'
    gem 'activeresource', github: 'rails/activeresource', branch: 'master'
    gem 'shopify_app', "~> 7.2"
